#include <bits/stdc++.h>

using namespace std;

/// @brief default seed used to the generation, if not specified
int DEFAULT_SEED = 2323;

/// @brief default multiplier used to the generation, if not specified
int DEFAULT_MULTIPLIER = 69; 

/// @brief default increment used to the generation, if not specified
int DEFAULT_INCREMENT = 13;

/// @brief default modulus used to the generation, if not specified
int DEFAULT_MODULUS = 29;

/// @brief simple linear congruential generator (LCG)
class SimpleLCGGenerator{
    public:
    /// @brief intial seed used in the generation process
    int Seed;
    /// @brief multiplier factor of the LCG
    int Multiplier; 
    /// @brief increment factor of the LCG
    int Increment;
    /// @brief modulus factor of the LCG
    int Modulus;

    /// @brief constructs the generator with all specified parameters
    /// @param seed intial seed used in the generation process
    /// @param multiplier multiplier factor of the LCG
    /// @param increment increment factor of the LCG
    /// @param modulus modulus factor of the LCG
    SimpleLCGGenerator(int seed, int multiplier, int increment, int modulus){
        Seed = seed;
        Multiplier = multiplier; 
        Increment = increment;
        Modulus = modulus;
    }

    /// @brief constructs the generator with default seed
    /// @param multiplier multiplier factor of the LCG
    /// @param increment increment factor of the LCG
    /// @param modulus modulus factor of the LCG
    SimpleLCGGenerator(int multiplier, int increment, int modulus){
        Seed = DEFAULT_SEED;
        Multiplier = multiplier; 
        Increment = increment;
        Modulus = modulus;
    }

    /// @brief constructs the generator with all default parameters
    SimpleLCGGenerator(){
        Seed = DEFAULT_SEED;
        Multiplier = DEFAULT_MULTIPLIER; 
        Increment = DEFAULT_INCREMENT;
        Modulus = DEFAULT_MODULUS;
    }

    public:
    /// @brief generates a list with n = size pseudo-random numbers, using a linear congruential generator (LCG)
    /// @param size size of the generated sequence
    /// @return vector <int> with the pseudo-random numbers
    vector <int> GenerateList(int size){
        vector <int> new_list;

        // takes the previous element as a seed to generate the next — seed updating by the Generate() method
        for(int i = 0; i < size; i++)
            new_list.push_back(Generate(Seed));

        return new_list;
    }

    public:
    /// @brief returns a pseudo-random number, using a linear congruential generator (LCG)
    /// @param seed intial seed used in the generation process
    /// @param multiplier multiplier factor of the LCG
    /// @param increment increment factor of the LCG
    /// @param modulus modulus factor of the LCG
    /// @return pseudo-random number generated by LCG
    int Generate(int seed){
        int new_number;
        new_number = ((seed * Multiplier) + Increment) % Modulus;
        Seed = new_number;
        return new_number;
    }

    public:
    /// @brief generates a pseudo-random number, using a linear congruential generator (LCG) (default seed)
    /// @param seed intial seed used in the generation process
    /// @param multiplier multiplier factor of the LCG
    /// @param increment increment factor of the LCG
    /// @param modulus modulus factor of the LCG
    /// @return pseudo-random number generated by LCG
    int Generate(){
        int new_number;
        new_number = ((Seed * Multiplier) + Increment) % Modulus;
        Seed = new_number;
        return new_number;
    }
};